#!/bin/sh
#
# domino-api   Start the domino api/web daemon
#
# chkconfig: 2345 99 01
# description: Domino is a monitoring frontend
# processname: python
# config: /opt/domino/domino.conf
# pidfile: /var/run/domino-api.pid
### BEGIN INIT INFO
# Provides:          domino-api
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Monitoring frontend.
# Description:       Domino is a monitoring frontend
### END INIT INFO

# Author: Chad Barraford <cbarraford@gmail.com>
NAME=domino-api
DAEMON=/opt/domino/bin/domino-api
DAEMON_ARGS="-p /var/run/domino-api.pid"
PIDFILE=/var/run/domino-api.pid
SCRIPTNAME=/etc/init.d/domino-api

. /etc/rc.d/init.d/functions

start() {
  echo -n $"Starting $NAME: "
  daemon --pidfile $PIDFILE $DAEMON $DAEMON_ARGS
  retval=$?
  if [ $retval -eq 0 ]; then
    echo_success
    echo
  else
    echo_failure
    echo
  fi
  return $retval
}

stop() {
  echo -n $"Stopping $NAME: "
  killproc -p $PIDFILE $NAME
  retval=$?
  echo
  return $retval
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p $PIDFILE $NAME
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|status}"
    exit 2
    ;;
esac

exit $?
