#! /bin/bash

set -e
buildroot=$(dirname $(readlink -f "$0"))
mkdir -p ${buildroot}/{RPMS,BUILD,BUILDROOT}
rpmbuild --verbose \
    --define "_sourcedir ${buildroot}" \
    --define "_topdir ${buildroot}" \
    -bb "${buildroot}/spec"
